name: build
on:
  push: {}
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --check-files
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - name: build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-artifact
          path: dist
